apiVersion: v1
kind: Service

metadata:
  name: rsync-target
  namespace: ${NAMESPACE}

spec:
  selector:
    app: rsync-target

  type: LoadBalancer

  loadBalancerIP: ${LOADBALANCER_IP}

  ports:
  - port: ${SERVICE_PORT}
    targetPort: ${CONTAINER_PORT}
